# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-23 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u516c\u53f8\u540d\u79f0')),
                ('address', models.CharField(max_length=128, verbose_name='\u516c\u53f8\u5730\u5740')),
                ('bank_number', models.CharField(max_length=128, verbose_name='\u516c\u53f8\u8d26\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u5408\u540c\u540d\u79f0')),
                ('start_time', models.DateField(verbose_name='\u5408\u540c\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateField(verbose_name='\u5408\u540c\u7ed3\u675f\u65f6\u95f4')),
                ('stop_time', models.DateField(verbose_name='\u5408\u540c\u7ec8\u6b62\u65f6\u95f4')),
                ('customer', models.CharField(max_length=128, verbose_name='\u7528\u6237')),
                ('telephone', models.CharField(max_length=128, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('remark', models.CharField(max_length=256, verbose_name='\u5907\u6ce8')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contract.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u9500\u552e\u59d3\u540d')),
                ('telephone', models.CharField(max_length=128, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contract.Sales'),
        ),
    ]
